### ISSUE TITLE
Clarification on relationship of ethnicity with compensation and job satisfaction

### ISSUE THREAD

**Issue by amajee11us** [Ghost---Shadow/stackoverflow-developer-survey-analysis#1]
Just being curious here. Is there a way to verify the following relationships:
1. I would be earning the mmaximum with 10 -20 yrs of coding experience as a South Asian but my job satisfaction is pretty low.
2. compensation tends to increase after 40 yrs of experience, but satisfaction goes down for white/europeans. Is this boredom? Also, between 35 to 40 yrs, the compensation drops but satisfaction is soaring. I do not get this point :(.

**Comment by Ghost---Shadow** [comment]
1. Asian countries tend to have lower job satisfaction than western countries in general. The competence and empathy of the manager play a bigger role. People are slightly less satisfied in large companies than in small companies. There is a significant difference by industry. People in finance and logistics tend to be dissatisfied. Satisfaction by role also varies.
2. The datapoints at the far end are a bit sparse, it is best not to overthink and we should perhaps rule out the outliers as noise. That being said, "Losing hope in programming" is a major problem and quite a few people have made youtube videos on it.
